---
- name: Solr digs lsof
  yum:
    name: lsof
    state: present

- name: get Solr {{ solr_version }} via {{ solr_url }}
  get_url:
    url: '{{ solr_url }}'
    dest: '/tmp/{{ solr_url | basename }}'
  tags: solr

- name: Extract Solr {{ solr_version }} archive to /tmp
  unarchive:
    src: '/tmp/{{ solr_url | basename }}'
    dest: /tmp/
    remote_src: True
  tags: solr

- name: 'Solr service is installed and started: -i {{ solr_install_dir | default("/opt") }} -d {{ solr_home | default("/var/solr") }} -p {{ solr_port | default("8983") }} -u {{ solr_user | default("solr") }} -s {{ solr_service_name | default("solr") }}'
  shell: >
    /tmp/solr-{{ solr_version }}/bin/install_solr_service.sh
    /tmp/{{ solr_url | basename }}
    -p {{ solr_port | default("8983") }}
    -u {{ solr_user | default("solr") }}
    -i {{ solr_install_dir | default("/opt") }}
    -d {{ solr_home | default("/var/solr") }}
    -u {{ solr_user | default("solr") }}
    -s {{ solr_service_name | default("solr") }}
  args:
    creates: '{{ solr_install_dir | default("/opt") }}/solr-{{ solr_version }}/bin/solr'
  tags: solr

- name:  '{{ solr_user }}:{{ solr_group }} owns: {{ solr_install_dir | default("/opt") }}/solr-{{ solr_version }}, becase Solr is watching for undefined log dir and would fail on restart otherwise.'
  file:
    path: '{{ solr_install_dir | default("/opt") }}/solr-{{ solr_version }}'
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'

- name: Solr configuration is present
  template:
    src: solr.in.sh.j2
    owner: root
    group: '{{ solr_group }}'
    dest: /etc/default/solr.in.sh
    mode: 0610
    backup: yes
  notify: restart Solr

- name: Solr will start after restart
  service:
    name: solr
    enabled: yes
